// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WomenClothingStore.Infrastructure.Data;

#nullable disable

namespace WomenClothingStore.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("ProductSize", b =>
                {
                    b.Property<int>("ProductsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SizesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProductsId", "SizesId");

                    b.HasIndex("SizesId");

                    b.ToTable("ProductSize");
                });

            modelBuilder.Entity("WomenClothingStore.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Стильные и базовые футболки на каждый день",
                            Name = "Футболки"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Элегантные и модные юбки для любого сезона",
                            Name = "Юбки"
                        });
                });

            modelBuilder.Entity("WomenClothingStore.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Классическая хлопковая футболка прямого кроя.",
                            Name = "Базовая белая футболка",
                            Price = 1500m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Трендовая свободная футболка из плотного трикотажа.",
                            Name = "Футболка оверсайз с принтом",
                            Price = 2200m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Укороченная модель для активного отдыха и тренировок.",
                            Name = "Спортивная кроп-футболка",
                            Price = 1800m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Description = "Легкая плиссированная юбка нежного пастельного оттенка.",
                            Name = "Юбка-миди плиссе",
                            Price = 3500m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Description = "Стильная макси-юбка из плотного денима с эффектным разрезом.",
                            Name = "Джинсовая юбка с разрезом",
                            Price = 4200m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Description = "Элегантная юбка из эко-кожи для делового или вечернего образа.",
                            Name = "Кожаная юбка-карандаш",
                            Price = 4800m
                        });
                });

            modelBuilder.Entity("WomenClothingStore.Domain.Entities.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMain")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsMain = true,
                            ProductId = 1,
                            Url = "https://images.pexels.com/photos/1484799/pexels-photo-1484799.jpeg?auto=compress&cs=tinysrgb&w=600"
                        },
                        new
                        {
                            Id = 2,
                            IsMain = true,
                            ProductId = 2,
                            Url = "https://images.pexels.com/photos/2294342/pexels-photo-2294342.jpeg?auto=compress&cs=tinysrgb&w=600"
                        },
                        new
                        {
                            Id = 3,
                            IsMain = true,
                            ProductId = 3,
                            Url = "https://images.pexels.com/photos/3534523/pexels-photo-3534523.jpeg?auto=compress&cs=tinysrgb&w=600"
                        },
                        new
                        {
                            Id = 4,
                            IsMain = true,
                            ProductId = 4,
                            Url = "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=600&q=80"
                        },
                        new
                        {
                            Id = 5,
                            IsMain = true,
                            ProductId = 5,
                            Url = "https://images.unsplash.com/photo-1544441893-675973e31985?auto=format&fit=crop&w=600&q=80"
                        },
                        new
                        {
                            Id = 6,
                            IsMain = true,
                            ProductId = 6,
                            Url = "https://images.unsplash.com/photo-1509319117193-57bab727e09d?auto=format&fit=crop&w=600&q=80"
                        });
                });

            modelBuilder.Entity("WomenClothingStore.Domain.Entities.Size", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Size");
                });

            modelBuilder.Entity("ProductSize", b =>
                {
                    b.HasOne("WomenClothingStore.Domain.Entities.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WomenClothingStore.Domain.Entities.Size", null)
                        .WithMany()
                        .HasForeignKey("SizesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WomenClothingStore.Domain.Entities.Product", b =>
                {
                    b.HasOne("WomenClothingStore.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("WomenClothingStore.Domain.Entities.ProductImage", b =>
                {
                    b.HasOne("WomenClothingStore.Domain.Entities.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WomenClothingStore.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("WomenClothingStore.Domain.Entities.Product", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
