// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WomenClothingStore.Infrastructure.Data;

#nullable disable

namespace WomenClothingStore.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260613091459_UpdateProductImages2")]
    partial class UpdateProductImages2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("WomenClothingStore.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Стильные и базовые футболки на каждый день",
                            Emoji = "👕",
                            Name = "Футболки"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Элегантные и модные юбки для любого сезона",
                            Emoji = "👗",
                            Name = "Юбки"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Платья для любого повода — от casual до вечерних",
                            Emoji = "👘",
                            Name = "Платья"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Лёгкие блузки и рубашки на каждый день",
                            Emoji = "👚",
                            Name = "Блузки"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Удобные и модные брюки и джинсы",
                            Emoji = "👖",
                            Name = "Брюки"
                        });
                });

            modelBuilder.Entity("WomenClothingStore.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Классическая хлопковая футболка прямого кроя. Идеальная база любого гардероба.",
                            Name = "Базовая белая футболка",
                            Price = 1500m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Трендовая свободная футболка из плотного трикотажа с авторским принтом.",
                            Name = "Футболка оверсайз с принтом",
                            Price = 2200m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Укороченная модель для активного отдыха и тренировок. Влагоотводящий материал.",
                            Name = "Спортивная кроп-футболка",
                            Price = 1800m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Description = "Лёгкая плиссированная юбка нежного пастельного оттенка.",
                            Name = "Юбка-миди плиссе",
                            Price = 3500m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Description = "Стильная макси-юбка из плотного денима с эффектным разрезом.",
                            Name = "Джинсовая юбка с разрезом",
                            Price = 4200m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Description = "Элегантная юбка из эко-кожи для делового или вечернего образа.",
                            Name = "Кожаная юбка-карандаш",
                            Price = 4800m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            Description = "Воздушное платье из натурального хлопка с цветочным принтом.",
                            Name = "Летнее платье в цветочек",
                            Price = 5200m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            Description = "Изысканное платье-футляр из бархата для особых случаев.",
                            Name = "Вечернее чёрное платье",
                            Price = 8900m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            Description = "Универсальное платье свободного кроя в классическую клетку.",
                            Name = "Платье-рубашка в клетку",
                            Price = 4600m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 4,
                            Description = "Нежная блузка из искусственного шёлка с V-образным вырезом.",
                            Name = "Шёлковая блузка молочная",
                            Price = 3800m
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 4,
                            Description = "Лёгкая льняная рубашка — идеальный выбор для жаркого лета.",
                            Name = "Льняная рубашка оверсайз",
                            Price = 3200m
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 4,
                            Description = "Романтичная блузка с пышными рукавами-буфами из шифона.",
                            Name = "Блузка с объёмными рукавами",
                            Price = 4100m
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 5,
                            Description = "Классические мом-джинсы с высокой посадкой из плотного денима.",
                            Name = "Прямые джинсы Mom-fit",
                            Price = 5500m
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 5,
                            Description = "Широкие брюки из льна — лёгкость и стиль в одном образе.",
                            Name = "Льняные брюки палаццо",
                            Price = 4700m
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 5,
                            Description = "Прямые брюки со стрелками из костюмной ткани. Офис и вечер.",
                            Name = "Чёрные классические брюки",
                            Price = 5100m
                        });
                });

            modelBuilder.Entity("WomenClothingStore.Domain.Entities.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMain")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsMain = true,
                            ProductId = 1,
                            Url = "https://images.pexels.com/photos/1484799/pexels-photo-1484799.jpeg?auto=compress&cs=tinysrgb&w=600"
                        },
                        new
                        {
                            Id = 2,
                            IsMain = true,
                            ProductId = 2,
                            Url = "https://images.pexels.com/photos/2294342/pexels-photo-2294342.jpeg?auto=compress&cs=tinysrgb&w=600"
                        },
                        new
                        {
                            Id = 3,
                            IsMain = true,
                            ProductId = 3,
                            Url = "https://images.pexels.com/photos/6311392/pexels-photo-6311392.jpeg?auto=compress&cs=tinysrgb&w=600"
                        },
                        new
                        {
                            Id = 4,
                            IsMain = true,
                            ProductId = 4,
                            Url = "https://images.pexels.com/photos/4690501/pexels-photo-4690501.jpeg?auto=compress&cs=tinysrgb&w=600"
                        },
                        new
                        {
                            Id = 5,
                            IsMain = true,
                            ProductId = 5,
                            Url = "https://images.pexels.com/photos/23947043/pexels-photo-23947043.jpeg?auto=compress&cs=tinysrgb&w=600"
                        },
                        new
                        {
                            Id = 6,
                            IsMain = true,
                            ProductId = 6,
                            Url = "https://images.pexels.com/photos/5217676/pexels-photo-5217676.jpeg?auto=compress&cs=tinysrgb&w=600"
                        },
                        new
                        {
                            Id = 7,
                            IsMain = true,
                            ProductId = 7,
                            Url = "https://images.pexels.com/photos/972995/pexels-photo-972995.jpeg?auto=compress&cs=tinysrgb&w=600"
                        },
                        new
                        {
                            Id = 8,
                            IsMain = true,
                            ProductId = 8,
                            Url = "https://images.pexels.com/photos/1755428/pexels-photo-1755428.jpeg?auto=compress&cs=tinysrgb&w=600"
                        },
                        new
                        {
                            Id = 9,
                            IsMain = true,
                            ProductId = 9,
                            Url = "https://images.pexels.com/photos/2466756/pexels-photo-2466756.jpeg?auto=compress&cs=tinysrgb&w=600"
                        },
                        new
                        {
                            Id = 10,
                            IsMain = true,
                            ProductId = 10,
                            Url = "https://images.pexels.com/photos/7691334/pexels-photo-7691334.jpeg?auto=compress&cs=tinysrgb&w=600"
                        },
                        new
                        {
                            Id = 11,
                            IsMain = true,
                            ProductId = 11,
                            Url = "https://images.pexels.com/photos/9558912/pexels-photo-9558912.jpeg?auto=compress&cs=tinysrgb&w=600"
                        },
                        new
                        {
                            Id = 12,
                            IsMain = true,
                            ProductId = 12,
                            Url = "https://images.pexels.com/photos/9594428/pexels-photo-9594428.jpeg?auto=compress&cs=tinysrgb&w=600"
                        },
                        new
                        {
                            Id = 13,
                            IsMain = true,
                            ProductId = 13,
                            Url = "https://images.pexels.com/photos/1598507/pexels-photo-1598507.jpeg?auto=compress&cs=tinysrgb&w=600"
                        },
                        new
                        {
                            Id = 14,
                            IsMain = true,
                            ProductId = 14,
                            Url = "https://images.pexels.com/photos/9558706/pexels-photo-9558706.jpeg?auto=compress&cs=tinysrgb&w=600"
                        },
                        new
                        {
                            Id = 15,
                            IsMain = true,
                            ProductId = 15,
                            Url = "https://images.pexels.com/photos/3766210/pexels-photo-3766210.jpeg?auto=compress&cs=tinysrgb&w=600"
                        });
                });

            modelBuilder.Entity("WomenClothingStore.Domain.Entities.ProductSize", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SizeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProductId", "SizeId");

                    b.HasIndex("SizeId");

                    b.ToTable("ProductSizes");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            SizeId = 1,
                            StockQuantity = 3
                        },
                        new
                        {
                            ProductId = 1,
                            SizeId = 2,
                            StockQuantity = 8
                        },
                        new
                        {
                            ProductId = 1,
                            SizeId = 3,
                            StockQuantity = 12
                        },
                        new
                        {
                            ProductId = 1,
                            SizeId = 4,
                            StockQuantity = 5
                        },
                        new
                        {
                            ProductId = 1,
                            SizeId = 5,
                            StockQuantity = 0
                        },
                        new
                        {
                            ProductId = 2,
                            SizeId = 2,
                            StockQuantity = 4
                        },
                        new
                        {
                            ProductId = 2,
                            SizeId = 3,
                            StockQuantity = 7
                        },
                        new
                        {
                            ProductId = 2,
                            SizeId = 4,
                            StockQuantity = 6
                        },
                        new
                        {
                            ProductId = 2,
                            SizeId = 5,
                            StockQuantity = 2
                        },
                        new
                        {
                            ProductId = 3,
                            SizeId = 1,
                            StockQuantity = 5
                        },
                        new
                        {
                            ProductId = 3,
                            SizeId = 2,
                            StockQuantity = 9
                        },
                        new
                        {
                            ProductId = 3,
                            SizeId = 3,
                            StockQuantity = 0
                        },
                        new
                        {
                            ProductId = 3,
                            SizeId = 4,
                            StockQuantity = 3
                        },
                        new
                        {
                            ProductId = 4,
                            SizeId = 1,
                            StockQuantity = 2
                        },
                        new
                        {
                            ProductId = 4,
                            SizeId = 2,
                            StockQuantity = 5
                        },
                        new
                        {
                            ProductId = 4,
                            SizeId = 3,
                            StockQuantity = 8
                        },
                        new
                        {
                            ProductId = 4,
                            SizeId = 4,
                            StockQuantity = 4
                        },
                        new
                        {
                            ProductId = 4,
                            SizeId = 5,
                            StockQuantity = 1
                        },
                        new
                        {
                            ProductId = 5,
                            SizeId = 2,
                            StockQuantity = 3
                        },
                        new
                        {
                            ProductId = 5,
                            SizeId = 3,
                            StockQuantity = 6
                        },
                        new
                        {
                            ProductId = 5,
                            SizeId = 4,
                            StockQuantity = 0
                        },
                        new
                        {
                            ProductId = 5,
                            SizeId = 5,
                            StockQuantity = 4
                        },
                        new
                        {
                            ProductId = 6,
                            SizeId = 1,
                            StockQuantity = 0
                        },
                        new
                        {
                            ProductId = 6,
                            SizeId = 2,
                            StockQuantity = 4
                        },
                        new
                        {
                            ProductId = 6,
                            SizeId = 3,
                            StockQuantity = 7
                        },
                        new
                        {
                            ProductId = 6,
                            SizeId = 4,
                            StockQuantity = 3
                        },
                        new
                        {
                            ProductId = 7,
                            SizeId = 1,
                            StockQuantity = 6
                        },
                        new
                        {
                            ProductId = 7,
                            SizeId = 2,
                            StockQuantity = 10
                        },
                        new
                        {
                            ProductId = 7,
                            SizeId = 3,
                            StockQuantity = 8
                        },
                        new
                        {
                            ProductId = 7,
                            SizeId = 4,
                            StockQuantity = 4
                        },
                        new
                        {
                            ProductId = 7,
                            SizeId = 5,
                            StockQuantity = 0
                        },
                        new
                        {
                            ProductId = 8,
                            SizeId = 1,
                            StockQuantity = 1
                        },
                        new
                        {
                            ProductId = 8,
                            SizeId = 2,
                            StockQuantity = 3
                        },
                        new
                        {
                            ProductId = 8,
                            SizeId = 3,
                            StockQuantity = 5
                        },
                        new
                        {
                            ProductId = 8,
                            SizeId = 4,
                            StockQuantity = 2
                        },
                        new
                        {
                            ProductId = 9,
                            SizeId = 2,
                            StockQuantity = 5
                        },
                        new
                        {
                            ProductId = 9,
                            SizeId = 3,
                            StockQuantity = 9
                        },
                        new
                        {
                            ProductId = 9,
                            SizeId = 4,
                            StockQuantity = 6
                        },
                        new
                        {
                            ProductId = 9,
                            SizeId = 5,
                            StockQuantity = 3
                        },
                        new
                        {
                            ProductId = 10,
                            SizeId = 1,
                            StockQuantity = 4
                        },
                        new
                        {
                            ProductId = 10,
                            SizeId = 2,
                            StockQuantity = 7
                        },
                        new
                        {
                            ProductId = 10,
                            SizeId = 3,
                            StockQuantity = 0
                        },
                        new
                        {
                            ProductId = 10,
                            SizeId = 4,
                            StockQuantity = 5
                        },
                        new
                        {
                            ProductId = 11,
                            SizeId = 2,
                            StockQuantity = 8
                        },
                        new
                        {
                            ProductId = 11,
                            SizeId = 3,
                            StockQuantity = 10
                        },
                        new
                        {
                            ProductId = 11,
                            SizeId = 4,
                            StockQuantity = 7
                        },
                        new
                        {
                            ProductId = 11,
                            SizeId = 5,
                            StockQuantity = 3
                        },
                        new
                        {
                            ProductId = 12,
                            SizeId = 1,
                            StockQuantity = 2
                        },
                        new
                        {
                            ProductId = 12,
                            SizeId = 2,
                            StockQuantity = 5
                        },
                        new
                        {
                            ProductId = 12,
                            SizeId = 3,
                            StockQuantity = 8
                        },
                        new
                        {
                            ProductId = 12,
                            SizeId = 4,
                            StockQuantity = 0
                        },
                        new
                        {
                            ProductId = 13,
                            SizeId = 2,
                            StockQuantity = 6
                        },
                        new
                        {
                            ProductId = 13,
                            SizeId = 3,
                            StockQuantity = 9
                        },
                        new
                        {
                            ProductId = 13,
                            SizeId = 4,
                            StockQuantity = 5
                        },
                        new
                        {
                            ProductId = 13,
                            SizeId = 5,
                            StockQuantity = 2
                        },
                        new
                        {
                            ProductId = 14,
                            SizeId = 1,
                            StockQuantity = 3
                        },
                        new
                        {
                            ProductId = 14,
                            SizeId = 2,
                            StockQuantity = 6
                        },
                        new
                        {
                            ProductId = 14,
                            SizeId = 3,
                            StockQuantity = 7
                        },
                        new
                        {
                            ProductId = 14,
                            SizeId = 4,
                            StockQuantity = 4
                        },
                        new
                        {
                            ProductId = 14,
                            SizeId = 5,
                            StockQuantity = 0
                        },
                        new
                        {
                            ProductId = 15,
                            SizeId = 2,
                            StockQuantity = 4
                        },
                        new
                        {
                            ProductId = 15,
                            SizeId = 3,
                            StockQuantity = 8
                        },
                        new
                        {
                            ProductId = 15,
                            SizeId = 4,
                            StockQuantity = 6
                        },
                        new
                        {
                            ProductId = 15,
                            SizeId = 5,
                            StockQuantity = 3
                        });
                });

            modelBuilder.Entity("WomenClothingStore.Domain.Entities.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorName = "Анна К.",
                            Comment = "Отличное качество! Ткань мягкая, не садится после стирки. Беру уже третью.",
                            CreatedAt = new DateTime(2025, 3, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = 1,
                            Rating = 5
                        },
                        new
                        {
                            Id = 2,
                            AuthorName = "Мария Д.",
                            Comment = "Хорошая футболка, но размер немного большемерит. Советую брать на размер меньше.",
                            CreatedAt = new DateTime(2025, 3, 15, 14, 30, 0, 0, DateTimeKind.Utc),
                            ProductId = 1,
                            Rating = 4
                        },
                        new
                        {
                            Id = 3,
                            AuthorName = "Екатерина",
                            Comment = "Просто в восторге! Принт очень чёткий, оверсайз посадка как на картинке.",
                            CreatedAt = new DateTime(2025, 4, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = 2,
                            Rating = 5
                        },
                        new
                        {
                            Id = 4,
                            AuthorName = "Ольга С.",
                            Comment = "Юбка великолепная! Ткань не мнётся, цвет нежный. Получила море комплиментов.",
                            CreatedAt = new DateTime(2025, 4, 5, 16, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = 4,
                            Rating = 5
                        },
                        new
                        {
                            Id = 5,
                            AuthorName = "Светлана",
                            Comment = "Юбка красивая, но пришла с небольшой затяжкой. Магазин решил вопрос быстро.",
                            CreatedAt = new DateTime(2025, 4, 12, 11, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = 4,
                            Rating = 3
                        },
                        new
                        {
                            Id = 6,
                            AuthorName = "Наталья Р.",
                            Comment = "Лучшее летнее платье! Лёгкое, не просвечивает. Уже заказала подруге в подарок.",
                            CreatedAt = new DateTime(2025, 5, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = 7,
                            Rating = 5
                        },
                        new
                        {
                            Id = 7,
                            AuthorName = "Виктория",
                            Comment = "Платье роскошное! Единственное — нужна правильная бижутерия, сама по себе выглядит просто.",
                            CreatedAt = new DateTime(2025, 5, 10, 20, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = 8,
                            Rating = 4
                        },
                        new
                        {
                            Id = 8,
                            AuthorName = "Ирина П.",
                            Comment = "Джинсы мечты! Высокая посадка скрывает всё что нужно, ткань плотная и не тянется.",
                            CreatedAt = new DateTime(2025, 5, 15, 13, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = 13,
                            Rating = 5
                        });
                });

            modelBuilder.Entity("WomenClothingStore.Domain.Entities.Size", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Sizes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Label = "XS",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Label = "S",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            Label = "M",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            Label = "L",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            Label = "XL",
                            SortOrder = 5
                        });
                });

            modelBuilder.Entity("WomenClothingStore.Domain.Entities.Product", b =>
                {
                    b.HasOne("WomenClothingStore.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("WomenClothingStore.Domain.Entities.ProductImage", b =>
                {
                    b.HasOne("WomenClothingStore.Domain.Entities.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WomenClothingStore.Domain.Entities.ProductSize", b =>
                {
                    b.HasOne("WomenClothingStore.Domain.Entities.Product", "Product")
                        .WithMany("ProductSizes")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WomenClothingStore.Domain.Entities.Size", "Size")
                        .WithMany("ProductSizes")
                        .HasForeignKey("SizeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Size");
                });

            modelBuilder.Entity("WomenClothingStore.Domain.Entities.Review", b =>
                {
                    b.HasOne("WomenClothingStore.Domain.Entities.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WomenClothingStore.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("WomenClothingStore.Domain.Entities.Product", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("ProductSizes");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("WomenClothingStore.Domain.Entities.Size", b =>
                {
                    b.Navigation("ProductSizes");
                });
#pragma warning restore 612, 618
        }
    }
}
